[package]
name = "website"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-web = "4.9.0"
askama = "0.12.1"
askama_actix = "0.14.0"
clap = "4.5.20"
askama_resolver = { path = "../askama_resolver" }
rust-embed = "8.5.0"
